name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Wheter to execute cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x

jobs:
    lint-test:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        outputs:
          deps-cache-key: ${{steps.cahe-key.outputs.CACHE_KEY}}
        steps:
            - name: Checkout cide
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
            - name: Calculate cache key
              id: cache-key
              run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: Testing
              run: npm run test
            - name: Linting
              run: echo "Linting..."

    build:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        outputs:
          deps-cache-key: ${{steps.cahe-key.outputs.CACHE_KEY}}
        steps:
            - name: Checkout cide
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
            - name: Calculate cache key
              id: cache-key
              run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
            - name: Building
              run: npm run build